apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-{{ item }}
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/redisdata"
