---
partitions:
  - disk: /dev/sdc
    no: 2
    size: 15000
  - disk: /dev/sdc
    no: 3
    size: 15000
  - disk: /dev/sdd
    no: 1
    size: 15000
  - disk: /dev/sdd
    no: 2
    size: 15000


filesystems:
  - mountpoint: "/data_fs1"
    device: "/dev/sdc2"
  - mountpoint: "/data_fs2"
    device: "/dev/sdc3"
