---
disks:
  disk1:
    - diskname: "/dev/sdc"
    - name: "/dev/sdc2"
      part_no: 2
      size: 5000
    - name: "/dev/sdc3"
      part_no: 3
      size: 5000
  disk2:
    - name: "/dev/sdd1"
      part_no: 1
      size: 5000
    - name: "/dev/sdd2"
      part_no: 2
      size: 5000

filesystems:
  - mountpoint: "/data_fs1"
    device: "/dev/sdc2"
  - mountpoint: "/data_fs2"
    device: "/dev/sdc3"
