---

- name: Update apt cache
  apt:
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Update dnf/yum cache
  yum:
    update_cache: true
  when: ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum'

- name: Install packages
  package:
    name: containerd 
  when: inventory_hostname in groups[rke2_servers_group_name]
  
- name: Download helm
  unarchive:
    src: "https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: True
  when: inventory_hostname in groups[rke2_servers_group_name]

- name: Configure helm
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    owner: root
    group: root
    mode: 0777
    remote_src: True
  when: inventory_hostname in groups[rke2_servers_group_name]

- name: Add RKE2 to PATH
  copy:
    content: "export PATH=$PATH:/var/lib/rancher/rke2/bin"
    dest: "/etc/profile.d/add_path.sh"
  when: inventory_hostname in groups[rke2_servers_group_name]
  
- name: Adding the path in the bashrc files
  lineinfile:
    dest: /root/.bashrc
    line: 'export PATH=$PATH:/var/lib/rancher/rke2/bin'
    insertafter: 'EOF'
    regexp: 'export PATH=\$PATH:/var/lib/rancher/rke2/bin'
    state: present
