---

- name: Get redis deployment files
  copy:
    src: redis-data
    dest: /tmp
  tags: [ rediscl, redisop ]

- name: Create namespace
  shell: bash -ic "kubectl create ns {{ item }}"
  ignore_errors: True
  with_items:
    - 'redis'
    - 'redis-operator'
  tags: [ rediscl, redisop ]

  
- name: Deploy redis operator
  shell: bash -ic "helm upgrade redis-operator /tmp/redis-data/charts/redis-operator-0.10.1.tgz --install -n redis-operator"
  tags: redisop
  
- name: test redis operator
  shell: bash -ic "helm test redis-operator --namespace redis-operator"
  tags: redisop
  
- name: Install redis-cli
  apt:
    name: redis-tools
    state: present
  tags: rediscl

- name: Create redis clusters
  include_tasks: redis-cluster.yaml
  tags: rediscl
  with_items :
    - 'cache-builder-redis'
    - 'anycable-redis'
    - 'linehaul-redis'
    - 'sidekiq-redis'
    - 'current-state-redis'
    - 'mocker-redis'
    - 'summarizer-redis'
