---

- name: Create kafka pv files 
  template:
    src: pv_kafka.yaml
    dest: "/tmp/pv_{{ item }}.yaml"
  with_items:
    - 'kafka_pv1'
    - 'kafka_pv2'
    - 'kafka_pv3'

- name: Create zk pv files 
  template:
    src: pv_zk.yaml
    dest: "/tmp/pv_{{ item }}.yaml"
  with_items:
    - 'zk_pv1'
    - 'zk_pv2'
    - 'zk_pv3'

- name: Create kafka PV
  shell: bash -ic "kubectl apply -f /tmp/pv_{{ item }}.yaml"
  with_items:
    - 'kafka_pv1'
    - 'kafka_pv2'
    - 'kafka_pv3'

- name: Create zk PV
  shell: bash -ic "kubectl apply -f /tmp/pv_{{ item }}.yaml"
  with_items:
    - 'zk_pv1'
    - 'zk_pv2'
    - 'zk_pv3'

- name: Create namespace
  shell: bash -ic "kubectl create ns kafka"
  ignore_errors: True

- name: Get kafka deployment file
  copy:
    src: kafka
    dest: /tmp

- name: Deploy kafka operator
  shell: bash -ic "kubectl create -f /tmp/kafka/kafka.yaml -n kafka"

- name: Deploy kafka
  shell: bash -ic "kubectl create -f /tmp/kafka/kafka-cluster.yaml -n kafka"

- name: Wait for pods to come up
  shell: bash -ic "kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n kafka"

