---

- name: Create pv files 
  template:
    src: pv.yaml
    dest: "/tmp/pv_{{ item }}.yaml"
  with_items:
    - 'kafka_pv1'
    - 'kafka_pv2'
    - 'kafka_pv3'
    - 'kafka_pv4'
    - 'kafka_pv5'
    - 'kafka_pv6'


- name: Create PV
  shell: bash -ic "kubectl apply -f /tmp/pv_{{ item }}.yaml"
  with_items:
    - 'kafka_pv1'
    - 'kafka_pv2'
    - 'kafka_pv3'
    - 'kafka_pv4'
    - 'kafka_pv5'
    - 'kafka_pv6'

- name: Create namespace
  shell: bash -ic "kubectl create ns kafka"
  ignore_errors: True

- name: Get kafka deployment file
  copy:
    src: kafka
    dest: /tmp

- name: Deploy kafka operator
  shell: bash -ic "kubectl create -f /tmp/kafka/kafka.yaml -n kafka"

- name: Deploy kafka
  shell: bash -ic "kubectl create -f /tmp/kafka/kafka-cluster.yaml -n kafka"

- name: Wait for pods to come up
  shell: bash -ic "kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n kafka"

