---
- name: set vars
  set_fact:
    device: "{{ item.device}}"
    mountpoint: "{{ item.mountpoint}}"

- name: Create file systems
  filesystem:
    fstype: "{{ fstype }}"
    dev: "{{ device }}"
    opts: "{{ fs_mkfs_opts | default(default_mkfs_opts) }}"
    force: "{{ fs_force | default(default_force | bool) }}"

- name: Mount file systems
  mount:
    path: "{{ mountpoint }}"
    src: "{{ device }}"
    fstype: "{{ fstype | default(default_fstype) }}"
    opts: "{{ fs_mount_opts | default(default_mount_opts) }}"
    state: "{{ mount_state | default(default_state) }}"

- name: Set owner on file systems
  file:
    path: "{{ mountpoint }}"
    owner: "{{ owner | default(default_owner) }}"
    group: "{{ group | default(default_group) }}"
    mode: "{{ mode | default(default_mode) }}"
