apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  labels:
    team: loco
  name: loco-pgdb
  namespace: locopgdb
spec:
  allowedSourceRanges: null
  numberOfInstances: 3
  users:
    linehaul:  # database owner
    - superuser
    - createdb
  databases:
    telematics_db: linehaul
    fuel_db: linehaul
    summarizer_db: linehaul
    movement_db: linehaul
    geocoder_db: linehaul
    mocker_db: linehaul
    provider_db: linehaul
    datamocker_db: linehaul
    linehaul_db: linehaul
    alerts_db: linehaul
  postgresql:
    version: "14"
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: loco
  volume:
    size: 20Gi
