---

- name: display info
  parted:
    device: "{{ item.disk}}"
    unit: MB
  register:  disk_info

- name: set vars
  set_fact:
    endpoint: "{{ disk_info.partitions[-1].end }}"
    endnum:  "{{ disk_info.partitions[-1].num }}"
    part_size: "{{ item.size }}"
    disk: "{{ item.disk}}"
    mode: "{{ item.mode }}"
    vgname: "{{ item.vgname }}"
    label: "{{ item.label }}"
    pvlist: ""

- name: create partition
  parted:
    device: "{{ disk }}"
    part_type: logical
    label: "{{ label }}"
    number: "{{ (endnum | int | abs) + 1 }}"
    part_start: "{{ (endpoint | int | abs) + 1 }}MB"
    part_end: "{{ (endpoint | int | abs) + 1 + (part_size | int | abs) }}MB"
    flags: [ lvm ]
    unit: MB
    state: present

- name: create vg
  lvg:
    vg: "{{ vgname }}"
    pvs: "{{ disk + ((endnum | int | abs) + 1) | string}}"
  when:  mode  == "new"

- name: extend vg
  shell: |
    vgextend "{{ vgname }}" "{{ disk + ((endnum | int | abs) + 1) | string}}"
  when:  mode  == "extend"
