---

- name: vg create or extend
  include_tasks: create_vg.yaml
  tags: vg
  with_items : "{{ hostvars[inventory_hostname].vg }}"
- name: fs create or extend
  include_tasks: create_lvm_fs.yaml
  tags: fs
  with_items : "{{ hostvars[inventory_hostname].fs }}"
