---  
      
- name: copy script 
  copy:
    src: files/format_minio_disks.sh
    dest: /tmp/format_minio_disks.sh
    mode: 0744

      
- name: run script to format disks
  shell: /tmp/format_minio_disks.sh
  register: disks_to_format

 
- name: find if disk is formated and format it
  
  delegate_to: "{{ k8s_master }}"
  vars: 
    - ansible_ssh_user: deployer
    - ansible_ssh_pass: deployer
  become: true
  debug:
    msg: "{{ item.split(',') | first }}"
  
  with_items: "{{ disks_to_format.stdout_lines }}"

