---

- name: Create the RKE2 config dir
  file:
    state: directory
    path: /etc/rancher/rke2
    owner: root
    group: root
    mode: 0755

- name: Copy RKE2 config
  template:
    src: templates/config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644

- name: Copy Containerd Registry Configuration file
  template:
    src: "{{ rke2_custom_registry_path }}"
    dest: /etc/rancher/rke2/registries.yaml
    owner: root
    group: root
    mode: 0644
  when: rke2_custom_registry | bool

- name: Start RKE2 service on the rest of the nodes
  systemd:
    name: "rke2-{{ rke2_type }}.service"
    state: started
    enabled: true
  retries: 10
  delay: 3
  register: result
  environment:
    RKE2_TOKEN: "{{ rke2_token }}"

- name: Wait for remaining nodes to be ready
  shell: |
   set -o pipefail
   /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes | grep " Ready" | wc -l
  args:
    executable: /bin/bash
  changed_when: false
  register: all_ready_nodes
  until:
    - groups[rke2_cluster_group_name] | length == all_ready_nodes.stdout | int
  retries: 100
  delay: 15
  delegate_to: "{{ active_server | default(groups[rke2_servers_group_name].0) }}"
  run_once: true
