apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ item }}
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafkazkdata"
