  - name: Deploy minio 
    hosts: all
    become: yes
    
    tasks:
      - name: copy script 
        copy:
          src: files/format_minio_disks.sh
          dest: /tmp/format_minio_disks.sh
          mode: 0744
      
      - name: run script to format disks
        shell: /tmp/format_minio_disks.sh
      
      - name: Fetch the file from remote to local
        fetch: src=/tmp/diskhostmapping dest=/tmp/diskhostmapping{{inventory_hostname}} mode=0777 flat=yes
