  - name: Deploy minio 
    hosts: all
    become: yes
    
    tasks:
      - name: copy script 
        copy:
          src: files/format_minio_disks.sh
          dest: /tmp/format_minio_disks.sh
          mode: 0744
      
      - name: run script to format disks
        shell: /tmp/format_minio_disks.sh
        register: disks_to_format
      
      - name: display
        debug:
          var: disks_to_format.stdout | list
