---
- name: display info
  parted:
    device: "{{ fs_device }}"
    unit: MB
  register: sda_info
- name: set vars
  set_fact:
      endpoint: "{{ sda_info.partitions[-1].end }}"
      endnum:  "{{ sda_info.partitions[-1].num }}"
- debug:
    var: "{{ endpoint | int + 1 }}"
- name: create partition
  parted:
    device: "{{ fs_device }}"
    label: gpt
    part_type: logical
    number: "{{ (endnum | int | abs) + 1 }}"
    part_start: "{{ (endpoint | int | abs) + 1 }}MB"
    part_end: "{{ (endpoint | int | abs) + 1 + 1024 }}MB"
    unit: MB
    state: present
