---
- name: create partition
  parted:
    device: "{{ fs_device }}"
    label: gpt
    part_type: logical
    number: "1"
    part_start: "0GB"
    part_end: "15GB"
    unit: GB
    state: present

- name: initialize partition
  shell: dd if=/dev/zero of=/dev/sdc1 bs=1M count=128 status=progress
  register: result
