---
- name: create partition1
  parted:
    device: "{{ fs_device }}"
    label: gpt
    part_type: logical
    number: "1"
    part_start: "0MB
    part_end: "16000MB
    unit: MB
    state: present
    
- name: create partition2
  parted:
    device: "{{ fs_device }}"
    label: gpt
    part_type: logical
    number: "2"
    part_start: "16001MB
    part_end: "31000MB
    unit: MB
    state: present

- name: initialize partition
  shell: dd if=/dev/zero of=/dev/sdc1 bs=1M count=128 status=progress
  register: result
