---
- name: display info
  parted:
    device: "{{ fs_device }}"
    unit: MB
  register: sda_info
- name: set vars
  set_fact:
      endpoint: "{{ sda_info.partitions[-1].end }}"
      endnum:  "{{ sda_info.partitions[-1].num }}"
- debug:
    var: "{{ endpoint | int + 1 }}"
- name: create partition
  parted:
    device: "{{ fs_device }}"
    label: gpt
    part_type: logical
    number: "{{ (endnum | int | abs) + 1 }}"
    part_start: "{{ (endpoint | int | abs) + 1 }}MB"
    part_end: "{{ (endpoint | int | abs) + 1 + 1024 }}MB"
    unit: MB
    state: present
- name: Create file systems
  filesystem:
    fstype: "{{ fstype | default(default_fstype) }}"
    dev: "{{ fs_device + endnum }}"
    opts: "{{ fs_mkfs_opts | default(default_mkfs_opts) }}"
    force: "{{ fs_force | default(default_force | bool) }}"

- name: Mount file systems
  mount:
    path: "{{ mountpoint }}"
    src: "{{ fs_device + endnum }}"
    fstype: "{{ fstype | default(default_fstype) }}"
    opts: "{{ fs_mount_opts | default(default_mount_opts) }}"
    state: "{{ mount_state | default(default_state) }}"

- name: Set owner on file systems
  file:
    path: "{{ mountpoint }}"
    owner: "{{ owner | default(default_owner) }}"
    group: "{{ group | default(default_group) }}"
    mode: "{{ mode | default(default_mode) }}"